services:
    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'

    postgres_adonis:
        image: postgres
        container_name: postgres_adonis
        environment:
            POSTGRES_PASSWORD: 'postgres'
        ports:
            - '5432:5432'
        volumes:
            - postgres_adonis:/var/lib/postgresql
        networks:
            - network_adonis

networks:
    network_adonis:
        driver: bridge

volumes:
    postgres_adonis:
        driver: local
